### ISSUE TITLE
Bulk request with empty body

### ISSUE THREAD

**Issue by corest** [seecloud/security#17]
After running security checker it logs next errors

> 2016-12-28 18:03:39 - urllib3.connectionpool - DEBUG - http://127.0.0.1:9200 "PUT /ms_security_region1 HTTP/1.1" 400 411
> 2016-12-28 18:03:39 - elasticsearch - WARNING - PUT http://127.0.0.1:9200/ms_security_region1 [status:400 request:0.003s]
> 2016-12-28 18:03:39 - elasticsearch - DEBUG - > {"mappings": {"issue": {"properties": {"resolved_at": {"type": "date", "format": "yyyy-MM-dd HH:mm:ss Z"}, "user_id": {"type": "keyword"}, "description": {"type": "text"}, "confirmed_at": {"type": "date", "format": "yyyy-MM-dd HH:mm:ss Z"}, "tenant_id": {"type": "keyword"}, "region": {"type": "keyword"}, "discovered_at": {"type": "date", "format": "yyyy-MM-dd HH:mm:ss Z"}, "type": {"type": "keyword"}, "id": {"type": "keyword"}, "data": {"type": "text"}}}}}
> 2016-12-28 18:03:39 - elasticsearch - DEBUG - < {"error":{"root_cause":[{"type":"index_already_exists_exception","reason":"index [ms_security_region1/WuvseIp5R7uPkp3zkBDHbg] already exists","index_uuid":"WuvseIp5R7uPkp3zkBDHbg","index":"ms_security_region1"}],"type":"index_already_exists_exception","reason":"index [ms_security_region1/WuvseIp5R7uPkp3zkBDHbg] already exists","index_uuid":"WuvseIp5R7uPkp3zkBDHbg","index":"ms_security_region1"},"status":400}
> 2016-12-28 18:03:39 - security.checker - ERROR - Error running task
> Traceback (most recent call last):
>   File "build/bdist.linux-x86_64/egg/security/checker.py", line 64, in run
>     schedule.run_pending()
>   File "build/bdist.linux-x86_64/egg/schedule/__init__.py", line 462, in run_pending
>     default_scheduler.run_pending()
>   File "build/bdist.linux-x86_64/egg/schedule/__init__.py", line 75, in run_pending
>     self._run_job(job)
>   File "build/bdist.linux-x86_64/egg/schedule/__init__.py", line 129, in _run_job
>     ret = job.run()
>   File "build/bdist.linux-x86_64/egg/schedule/__init__.py", line 377, in run
>     ret = self.job_func()
>   File "build/bdist.linux-x86_64/egg/security/checker.py", line 58, in _discover
>     plugin.issue_types)
>   File "build/bdist.linux-x86_64/egg/security/storage.py", line 73, in update_issues
>     self.backend.commit(region)
>   File "build/bdist.linux-x86_64/egg/security/elastic.py", line 136, in commit
>     retval = self.es.bulk(self.body, self.index + region)
>   File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 71, in _wrapped
>     return func(*args, params=params, **kwargs)
>   File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 1094, in bulk
>     raise ValueError("Empty value passed for a required argument 'body'.")
> ValueError: Empty value passed for a required argument 'body'.

**Comment by corest** [comment]
Solved with https://github.com/seecloud/security/pull/20
